services:
  mc-server-image:
    build:
      context: .
      dockerfile: Dockerfile.mc
    image: plugin-jam-mc-server
    entrypoint: ["echo", "image built"]
  bot:
    image: ghcr.io/devcordde/plugin-jam-bot:latest
    depends_on:
      mc-server-image:
        condition: service_completed_successfully
    volumes:
      - ./data/bot/config:/app/config
      - ./data/bot/plugins:/app/plugins
      - ./data/bot/servers:/app/servers
      - ./data/bot/template:/app/template
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - plugin-jam-network
  velocity:
    build:
      context: .
      dockerfile: Dockerfile.velocity
    tty: true
    environment:
      EULA: "TRUE"
      TYPE: VELOCITY
      JVM_DD_OPTS: javalin.port=30000
    volumes:
      - ./data/velocity/config:/config
    networks:
      - plugin-jam-network
  lobby:
    image: itzg/minecraft-server:latest
    stdin_open: true
    tty: true
    environment:
      VERSION: 1.21
      TYPE: PAPER
      MEMORY: 2G
    volumes:
      - ./data/lobby:/data
    networks:
      - plugin-jam-network

networks:
  plugin-jam-network:
    name: plugin-jam-network
    driver: bridge
