services:
  bot:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./data/bot/config/config.yml:/app/config/config.yml
      - ./data/bot/plugins:/app/plugins
      - ./data/bot/servers:/app/servers
      - ./data/bot/template:/app/template
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - 131
  database:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5433:5432"
  velocity:
    image: itzg/mc-proxy:latest
    tty: true
    environment:
      EULA: "TRUE"
      TYPE: VELOCITY
      JVM_DD_OPTS: javalin.port=30000
    volumes:
      - ./data/velocity/config:/config
      - ./data/velocity/plugins:/plugins
  lobby:
    image: itzg/minecraft-server:latest
    stdin_open: true
    tty: true
    environment:
      VERSION: 1.21
      TYPE: PAPER
      MEMORY: 2G
    volumes:
      - ./data/lobby:/data
