apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_USER
              value: postgres
          image: postgres:14.2
          name: database
  selector:
    matchLabels:
      app: database
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
