name: Docker Build

on:
  release:
    types:
      - published
  push:
    tags:
    branches:
      - main
      - dev*
    paths:
      - bot/**

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Wait for checks to succeed
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          check-name: 'Verify Gradle'
          running-workflow-name: 'Verify'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-conclusions: success
      - name: Checkout
        uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Tag & Push branch image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - name: Tag & Push latest image
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
